version: '3.3'  # version of compose format

services:
  app:
    container_name: Landing
    build: 
      context: ./landing
    ports:
      - "5050:5050"
    depends_on:
      - addition
      - subtraction
      - multiplication
      - division
      - gcd
      - lcm
      - modulus
      - exponent
      - equal_to
    environment:
      - ADDITION_SERVICE_URL=http://addition-service:5051
      - SUBTRACTION_SERVICE_URL=http://subtraction-service:5052
      - MULTIPLICATION_SERVICE_URL=http://multiplication-service:5053
      - DIVISION_SERVICE_URL=http://division-service:5054
      - GCD_SERVICE_URL=http://gcd-service:5055
      - LCM_SERVICE_URL=http://lcm-service:5056
      - MODULUS_SERVICE_URL=http://modulus-service:5057
      - EXPONENT_SERVICE_URL=http://exponent-service:5058
      - EQUAL_TO_SERVICE_URL=http://greater-service:5059
    networks:
      - my-network
    # command: python app.py
    
  addition:
    container_name: addition-service
    build:
      context: ./addition
      dockerfile: Dockerfile
    # expose:
    #   - "5051"
    networks:
      - my-network
    # command: python addition.py

  subtraction:
    container_name: subtraction-service
    build:
      context: ./subtraction
      dockerfile: Dockerfile
    # expose:
    #   - "5052"
    networks:
      - my-network
    # command: python subtraction.py

  multiplication:
    container_name: multiplication-service
    build:
      context: ./multiplication
      dockerfile: Dockerfile
    # expose:
    #   - "5053"
    networks:
      - my-network
    # command: python multiplication.py

  division:
    container_name: division-service
    build:
      context: ./division
      dockerfile: Dockerfile
    # expose:
    #   - "5054"
    networks:
      - my-network
    # command: python division.py

  gcd:
    container_name: gcd-service
    build:
      context: ./gcd
      dockerfile: Dockerfile
    # expose:
    #   - "5055"
    networks:
      - my-network
    # command: python gcd.py

  lcm:
    container_name: lcm-service
    build:
      context: ./lcm
      dockerfile: Dockerfile
    # expose:
    #   - "5056"
    networks:
      - my-network
    # command: python lcm.py

  modulus:
    container_name: modulus-service
    build:
      context: ./modulus
      dockerfile: Dockerfile
    # expose:
    #   - "5057"
    networks:
      - my-network
    # command: python modulus.py

  exponent:
    container_name: exponent-service
    build:
      context: ./exponent
      dockerfile: Dockerfile
    # expose:
    #   - "5057"
    networks:
      - my-network

  equal_to:
    container_name: equal-service
    build:
      context: ./equal_to
      dockerfile: Dockerfile
    # expose:
    #   - "5058"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
